import * as T from './vendor/three.module.js';
import {V,clamp,makeJet,makeDestroyer,createWorld,ParticleSystem,glowTexture} from './world.js';
import {segmentDistanceSquared,targetInCone,waveAt} from './physics.js';

const $=id=>document.getElementById(id);
const isTouch=matchMedia('(pointer:coarse)').matches;
let renderer;
try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){$('error-screen').classList.remove('hidden');throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,isTouch?1.3:1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.setClearColor(0x7792a2);$('viewport').appendChild(renderer.domElement);
const scene=new T.Scene(),camera=new T.PerspectiveCamera(51,innerWidth/innerHeight,.4,25000);
const world=createWorld(scene,renderer),jet=makeJet();scene.add(jet);
const glow=glowTexture(),particles=new ParticleSystem(scene,glow,isTouch?500:850);
const jetLight=new T.PointLight(0xffb674,2.5,18);jetLight.position.set(0,0,7);jet.add(jetLight);
const enemyPrototype=makeJet(true),enemyPool=[];
for(let i=0;i<16;i++){const group=enemyPrototype.clone(true);group.userData.gear=group.children[group.children.length-1];group.traverse(o=>{if(o.isMesh&&o.material?.blending===T.AdditiveBlending)o.material=o.material.clone();});group.userData.flames=[];group.traverse(o=>{if(o.isMesh&&o.material?.blending===T.AdditiveBlending)group.userData.flames.push(o);});group.userData.gear.visible=false;group.visible=false;scene.add(group);enemyPool.push(group);}
const lineMaterials={friendly:new T.LineBasicMaterial({color:0xffe8bd,transparent:true,opacity:.95,blending:T.AdditiveBlending}),hostile:new T.LineBasicMaterial({color:0xff8964,transparent:true,opacity:1,blending:T.AdditiveBlending})};
const bulletPool=[];for(let i=0;i<180;i++){const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(new Float32Array(6),3).setUsage(T.DynamicDrawUsage));const mesh=new T.Line(g,lineMaterials.friendly);mesh.frustumCulled=false;mesh.visible=false;scene.add(mesh);bulletPool.push(mesh);}
const missilePrototype=new T.Group();
const missileBody=new T.Mesh(new T.CylinderGeometry(.14,.14,3.5,8),new T.MeshStandardMaterial({color:0xcbd7dc,metalness:.6,roughness:.35}));missileBody.rotation.x=Math.PI/2;missilePrototype.add(missileBody);
const missileNose=new T.Mesh(new T.ConeGeometry(.14,.7,8),new T.MeshStandardMaterial({color:0x566873,metalness:.6,roughness:.5}));missileNose.rotation.x=-Math.PI/2;missileNose.position.z=-2.1;missilePrototype.add(missileNose);
const missileFire=new T.Sprite(new T.SpriteMaterial({map:glow,color:0xffcc80,transparent:true,blending:T.AdditiveBlending,depthWrite:false}));missileFire.position.z=2.4;missileFire.scale.set(3,3,3);missilePrototype.add(missileFire);
const missilePool=[];for(let i=0;i<12;i++){const m=missilePrototype.clone(true);m.visible=false;scene.add(m);missilePool.push(m);}
const shadow=new T.Mesh(new T.PlaneGeometry(19,20),new T.MeshBasicMaterial({map:glow,color:0x081b24,transparent:true,opacity:.35,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=1.3;scene.add(shadow);

let phase='menu',previousPhase='play',loaded=false,time=0,clockTime=0,launchTime=0,score=0,kills=0,hp=100,wave=0,spawnTimer=0,gunTimer=0,missileCooldown=0,flareCooldown=0,invincible=0,flareTime=0,ammo=8,flares=3,ammoTimer=0,flareTimer=0,shake=0,damageAlpha=0,boss=null,quality='auto',smokeTimer=0;
let enemies=[],bullets=[],missiles=[],keys=new Set(),move=V(),joy={id:null,x:0,y:0},target=null,toastTimer=0,bannerTimer=0,uiTimer=0;
const aircraftVelocity=V(),cameraTarget=V(),lookTarget=V(),projected=V(),temp=V();
const markers=new Map();

// Audio is created only after a user gesture. Everything is synthesized locally.
let audio=null,engineOsc=null,engineGain=null,soundEnabled=false;
function initAudio(){if(audio)return;try{audio=new (window.AudioContext||window.webkitAudioContext)();engineOsc=audio.createOscillator();engineOsc.type='sawtooth';const low=audio.createBiquadFilter();low.type='lowpass';low.frequency.value=210;engineGain=audio.createGain();engineGain.gain.value=0;engineOsc.connect(low);low.connect(engineGain);engineGain.connect(audio.destination);engineOsc.frequency.value=42;engineOsc.start();}catch{soundEnabled=false;}}
function sound(kind){if(!soundEnabled||!audio)return;const t=audio.currentTime;if(kind==='explosion'){const len=audio.sampleRate*.65,buf=audio.createBuffer(1,len,audio.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const src=audio.createBufferSource();src.buffer=buf;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=600;const gain=audio.createGain();gain.gain.setValueAtTime(.45,t);gain.gain.exponentialRampToValueAtTime(.001,t+.65);src.connect(filter);filter.connect(gain);gain.connect(audio.destination);src.start();return;}
  const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);if(kind==='gun'){o.type='square';o.frequency.setValueAtTime(100,t);o.frequency.exponentialRampToValueAtTime(40,t+.07);g.gain.setValueAtTime(.018,t);g.gain.exponentialRampToValueAtTime(.001,t+.08);o.stop(t+.09);}else if(kind==='missile'){o.type='sawtooth';o.frequency.setValueAtTime(200,t);o.frequency.exponentialRampToValueAtTime(55,t+.45);g.gain.setValueAtTime(.1,t);g.gain.exponentialRampToValueAtTime(.001,t+.5);o.stop(t+.52);}else{o.type='sine';o.frequency.setValueAtTime(880,t);g.gain.setValueAtTime(.07,t);g.gain.exponentialRampToValueAtTime(.001,t+.13);o.stop(t+.14);}o.start(t);
}
function toggleSound(){initAudio();soundEnabled=!soundEnabled;audio?.resume().catch(()=>{});$('sound-on').style.display=soundEnabled?'block':'none';$('sound-off').style.display=soundEnabled?'none':'block';$('sound').setAttribute('aria-label',soundEnabled?'关闭声音':'开启声音');}

function showToast(text){$('toast').textContent=text;$('toast').classList.add('visible');toastTimer=2.8;}
function banner(title,subtitle,caption='AIR CONTACT'){ $('wave-title').textContent=title;$('wave-subtitle').textContent=subtitle;$('wave-caption').textContent=caption;$('wave-banner').classList.add('visible');bannerTimer=3.5; }
function setUI(id,on){$(id).classList.toggle('hidden',!on);}
function resetObjects(){for(const e of enemies){e.mesh.visible=false;removeMarker(e);}enemies=[];for(const b of bullets)b.mesh.visible=false;bullets=[];for(const m of missiles)m.mesh.visible=false;missiles=[];if(boss){scene.remove(boss.mesh);boss.mesh.traverse(o=>{if(o.isMesh){o.geometry.dispose();if(o.material?.map)o.material.map.dispose();o.material.dispose();}});removeMarker(boss);boss=null;}particles.clear();markers.forEach(m=>m.remove());markers.clear();setUI('boss-hud',false);}
function reset(){resetObjects();time=0;launchTime=0;score=0;kills=0;hp=100;wave=0;spawnTimer=1.8;gunTimer=0;missileCooldown=0;flareCooldown=0;invincible=0;flareTime=0;ammo=8;flares=3;ammoTimer=0;flareTimer=0;shake=0;target=null;aircraftVelocity.set(0,0,0);move.set(0,0,0);keys.clear();resetJoystick();jet.position.set(-9,14.93,28);jet.rotation.set(0,0,0);jet.userData.gear.visible=true;jet.userData.flames.forEach(f=>f.visible=false);jet.visible=true;damageAlpha=0;$('damage-flash').style.opacity='0';$('wave-banner').classList.remove('visible');bannerTimer=0;updateHUD();}
function start(){if(!loaded||phase==='launch')return;initAudio();audio?.resume().catch(()=>{});reset();phase='launch';setUI('start-screen',false);setUI('result-screen',false);setUI('pause-screen',false);setUI('hud',true);setUI('pause-button',true);setUI('controls',false);setUI('aim',false);$('mission-name').textContent='离舰起飞';$('mission-detail').textContent='弹射器已就绪';$('flight-message').textContent='塔台：甲板清空，允许起飞。';showToast('弹射准备 · 即将离舰');}
function menu(){reset();phase='menu';setUI('start-screen',true);setUI('result-screen',false);setUI('pause-screen',false);setUI('hud',false);setUI('controls',false);setUI('pause-button',false);setUI('aim',false);}
function pause(){if(!['play','launch'].includes(phase))return;previousPhase=phase;phase='paused';keys.clear();resetJoystick();setUI('pause-screen',true);if(engineGain&&audio)engineGain.gain.setTargetAtTime(0,audio.currentTime,.15);}
function resume(){if(phase!=='paused')return;phase=previousPhase;setUI('pause-screen',false);audio?.resume().catch(()=>{});}
function end(win){if(!['play','launch'].includes(phase))return;phase=win?'victory':'defeat';setUI('controls',false);setUI('aim',false);setUI('pause-button',false);setUI('boss-hud',false);$('wave-banner').classList.remove('visible');$('result-eyebrow').textContent=win?'MISSION COMPLETE':'MISSION ENDED';$('result-title').textContent=win?'海空肃清':'暂别蓝天';$('result-description').textContent=win?'敌方旗舰已被击毁。欢迎返航，飞行员。':'战机已失去作战能力。整备完毕后，再次出击。';$('result-score').textContent=String(score).padStart(5,'0');$('result-kills').textContent=String(kills).padStart(2,'0');$('result-time').textContent=formatTime(time);setUI('result-screen',true);keys.clear();resetJoystick();}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;}
function removeMarker(e){const m=markers.get(e);if(m){m.remove();markers.delete(e);}}
function damage(n){if(invincible>0||flareTime>0||phase!=='play')return;hp=Math.max(0,hp-n);invincible=.55;shake=1;damageAlpha=.8;sound('explosion');if(hp<=0){particles.burst(jet.position,90,1.5);jet.visible=false;end(false);}}
function damageEnemy(e,n){if(e.hp<=0)return;e.hp-=n;if(e.hp<=0){particles.burst(e.mesh.position,e.isBoss?100:45,e.isBoss?4:1.2);sound('explosion');shake=Math.max(shake,e.isBoss?.65:.2);score+=e.isBoss?8000:500;kills++;removeMarker(e);if(e.isBoss){e.mesh.visible=false;hp=Math.min(100,hp+10);end(true);}else{e.mesh.visible=false;enemies=enemies.filter(v=>v!==e);if(kills%5===0){hp=Math.min(100,hp+8);ammo=Math.min(8,ammo+2);showToast('编队击退 · 机体恢复 +8 · 导弹补给 +2');}}}else if(e.isBoss){$('boss-health').style.width=`${Math.max(0,e.hp/e.maxHp*100)}%`;particles.burst(e.mesh.position.clone().add(V(0,12,-15)),8,.6);}}

function spawnEnemy(xOffset=0){const mesh=enemyPool.find(m=>!m.visible);if(!mesh)return;const x=clamp(jet.position.x+(Math.random()-.5)*155+xOffset,-145,145),y=35+Math.random()*95;mesh.position.set(x,y,jet.position.z-650-Math.random()*140);mesh.rotation.set(0,Math.PI,0);mesh.scale.setScalar(1.1);mesh.visible=true;const e={mesh,hp:wave>=3?6:4,maxHp:wave>=3?6:4,age:0,fire:1.1+Math.random()*1.2,baseX:x,baseY:y,seed:Math.random()*10,isBoss:false};enemies.push(e);}
function spawnBoss(){const mesh=makeDestroyer(true);mesh.scale.setScalar(1.65);mesh.position.set(jet.position.x,0,jet.position.z-850);scene.add(mesh);boss={mesh,hp:250,maxHp:250,fire:1,age:0,isBoss:true};setUI('boss-hud',true);$('boss-health').style.width='100%';$('mission-name').textContent='海上打击';$('mission-detail').textContent='击毁敌方旗舰';banner('旗舰出现','降低高度，对准舰桥发起攻击','PRIORITY TARGET');ammo=8;flares=Math.max(2,flares);showToast('导弹补给完成 · 旗舰已进入雷达');}
function getTarget(narrow=false){let best=null,bestCost=Infinity;for(const e of boss&&boss.hp>0?[...enemies,boss]:enemies){const p=e.mesh.position.clone();if(e.isBoss)p.y=15;if(!targetInCone(jet.position,p,e.isBoss?1200:950))continue;const dz=jet.position.z-p.z,dx=p.x-jet.position.x,dy=p.y-jet.position.y;if(narrow&&(Math.abs(dx)>dz*.055+5||Math.abs(dy)>dz*.05+6))continue;const cost=dz+Math.abs(dx)*4+Math.abs(dy)*3;if(cost<bestCost){best=e;bestCost=cost;}}return best;}
function makeBullet(pos,dir,hostile=false){const mesh=bulletPool.find(m=>!m.visible);if(!mesh)return;mesh.visible=true;mesh.material=hostile?lineMaterials.hostile:lineMaterials.friendly;bullets.push({mesh,p:pos.clone(),prev:pos.clone(),v:dir.clone().multiplyScalar(hostile?245:920),life:hostile?5:1.35,hostile});}
function shootGun(){const gunTarget=getTarget(true);let dir=V(move.x*.065,move.y*.045,-1).normalize();if(gunTarget){const p=gunTarget.mesh.position.clone();if(gunTarget.isBoss)p.y=14;else p.addScaledVector(V(0,0,34),.15);dir=p.sub(jet.position).normalize();}for(const side of [-1,1]){const pos=jet.position.clone().add(V(side*.9,-.1,-6));makeBullet(pos,dir);particles.emit(pos,V(0,0,-30),.9,.055,0xffedc7);}sound('gun');}
function fireMissile(){if(phase!=='play')return false;if(missileCooldown>0)return false;if(ammo<=0){showToast('导弹正在补给');return false;}target=getTarget();if(!target){showToast('将敌机保持在机头前方以锁定');sound('beep');return false;}const mesh=missilePool.find(m=>!m.visible);if(!mesh)return false;ammo--;missileCooldown=1.5;mesh.visible=true;mesh.position.copy(jet.position).add(V(ammo%2?2.8:-2.8,-.8,0));missiles.push({mesh,target,dir:V(0,0,-1),age:0,trail:0});sound('missile');shake=.13;return true;}
function releaseFlares(){if(phase!=='play')return false;if(flareCooldown>0)return false;if(flares<=0){showToast('干扰弹正在补给');return false;}flares--;flareCooldown=4.5;flareTime=3.3;invincible=3.3;for(let i=0;i<42;i++){const side=i%2?1:-1;particles.emit(jet.position.clone().add(V(side,0,4)),V(side*(15+Math.random()*32),-5-Math.random()*10,70+Math.random()*30),2+Math.random()*2,1.4+Math.random()*2,0xffd889);}for(const b of bullets)if(b.hostile&&b.p.distanceTo(jet.position)<450){b.life=0;}showToast('干扰弹已释放 · 短暂规避攻击');sound('missile');return true;}

function updateBullets(dt){for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.life-=dt;b.prev.copy(b.p);b.p.addScaledVector(b.v,dt);if(b.hostile){if(segmentDistanceSquared(b.prev,b.p,jet.position)<15){damage(9);b.life=0;}}else{for(const e of boss&&boss.hp>0?[...enemies,boss]:enemies){const p=e.mesh.position.clone();if(e.isBoss)p.y=12;const r=e.isBoss?22:5.5;if(segmentDistanceSquared(b.prev,b.p,p)<r*r){damageEnemy(e,e.isBoss?1.5:1);b.life=0;break;}}}if(b.life<=0||b.p.y<0){b.mesh.visible=false;bullets.splice(i,1);continue;}const tail=b.p.clone().addScaledVector(b.v,-.018),arr=b.mesh.geometry.attributes.position;arr.setXYZ(0,b.p.x,b.p.y,b.p.z);arr.setXYZ(1,tail.x,tail.y,tail.z);arr.needsUpdate=true;}}
function updateMissiles(dt){for(let i=missiles.length-1;i>=0;i--){const m=missiles[i];m.age+=dt;const previous=m.mesh.position.clone();if(m.target.hp>0){const p=m.target.mesh.position.clone();if(m.target.isBoss)p.y=14;const d=p.sub(m.mesh.position).normalize();m.dir.lerp(d,Math.min(1,dt*(m.age<.22?1.2:5))).normalize();}m.mesh.position.addScaledVector(m.dir,dt*(260+Math.min(m.age,2)*180));m.mesh.quaternion.setFromUnitVectors(V(0,0,-1),m.dir);m.trail-=dt;if(m.trail<=0){m.trail=.025;particles.emit(m.mesh.position.clone(),V(0,1,15),2.2,.6,0xc2c8be,.27);particles.emit(m.mesh.position.clone(),V(),1.9,.11,0xffd798,.8);}const p=m.target.mesh.position.clone();if(m.target.isBoss)p.y=14;const hit=m.target.hp>0&&segmentDistanceSquared(previous,m.mesh.position,p)<(m.target.isBoss?750:55);if(hit){damageEnemy(m.target,m.target.isBoss?55:15);particles.burst(m.mesh.position,20,.7);}if(hit||m.age>5||m.mesh.position.y<0){m.mesh.visible=false;missiles.splice(i,1);}}}
function updateEnemies(dt){for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];e.age+=dt;e.fire-=dt;e.mesh.position.z+=dt*(28+wave*3);const amplitude=wave>=3?22:12;e.mesh.position.x=e.baseX+Math.sin(e.age*1.4+e.seed)*amplitude;e.mesh.position.y=e.baseY+Math.sin(e.age+e.seed)*5;e.mesh.rotation.z=Math.cos(e.age*1.4+e.seed)*.22;e.mesh.rotation.x=Math.cos(e.age+e.seed)*.035;animateFlames(e.mesh,clockTime,1);if(e.fire<=0&&e.mesh.position.distanceTo(jet.position)<700){e.fire=wave>=3?1.65:2.5;const origin=e.mesh.position.clone().add(V(0,0,6));const aimed=jet.position.clone().addScaledVector(aircraftVelocity,.2).sub(origin).normalize();makeBullet(origin,aimed,true);}if(e.mesh.position.distanceTo(jet.position)<12){damage(28);damageEnemy(e,100);}if(e.mesh.position.z>jet.position.z+70||e.age>14){e.mesh.visible=false;removeMarker(e);enemies.splice(i,1);}}
  if(boss&&boss.hp>0){boss.age+=dt;boss.mesh.position.z-=dt*165;boss.mesh.rotation.z=Math.sin(clockTime*.4)*.008;boss.fire-=dt;if(boss.fire<=0){boss.fire=.85;for(const x of [-6,6]){const origin=boss.mesh.position.clone().add(V(x,24,-4));makeBullet(origin,jet.position.clone().addScaledVector(aircraftVelocity,.25).sub(origin).normalize(),true);}}}
}
function animateFlames(model,t,strength){for(const f of model.userData.flames||[]){f.visible=true;f.scale.y=(.8+Math.sin(t*53+f.position.x)*.18)*strength;}}
function inputVector(){const kx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),ky=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0);move.x=clamp(kx+joy.x,-1,1);move.y=clamp(ky-joy.y,-1,1);}
function updatePlayer(dt){inputVector();aircraftVelocity.x=T.MathUtils.damp(aircraftVelocity.x,move.x*63,5,dt);aircraftVelocity.y=T.MathUtils.damp(aircraftVelocity.y,move.y*40,5,dt);aircraftVelocity.z=-165;jet.position.addScaledVector(aircraftVelocity,dt);jet.position.x=clamp(jet.position.x,-170,170);jet.position.y=clamp(jet.position.y,24,170);jet.rotation.z=T.MathUtils.damp(jet.rotation.z,-move.x*.5,5,dt);jet.rotation.x=T.MathUtils.damp(jet.rotation.x,move.y*.18,4,dt);jet.rotation.y=T.MathUtils.damp(jet.rotation.y,-move.x*.09,4,dt);animateFlames(jet,clockTime,1.2);jet.userData.gear.visible=false;if(hp<35){smokeTimer-=dt;if(smokeTimer<=0){smokeTimer=.06;particles.emit(jet.position.clone().add(V(0,0,5)),V(0,4,45),6,1.4,0x8a6c4c,.22);}}}
function updateLaunch(dt){launchTime+=dt;const t=launchTime,run=Math.min(3,t);jet.position.z=28-27.5*run*run-165*Math.max(0,t-3);jet.position.y=14.93+Math.max(0,t-3)*14;jet.rotation.x=t>3?.085:0;animateFlames(jet,clockTime,clamp(t*.4,.25,1.2));jet.userData.gear.visible=t<4.3;aircraftVelocity.z=-Math.min(t*55,165);if(t<1.7){$('mission-detail').textContent='弹射器加速';}else if(t<3){$('mission-detail').textContent='加速滑跑';}else{$('mission-detail').textContent='爬升中';$('flight-message').textContent='塔台：起飞成功，保持航向。';}
  if(t>=6.5){phase='play';time=0;setUI('controls',true);setUI('aim',true);$('mission-name').textContent='舰队防空';$('mission-detail').textContent='清除接近的敌机';$('flight-message').textContent=isTouch?'左侧摇杆飞行 · 对准敌机自动射击':'WASD 飞行 · 空格导弹 · F 干扰弹';banner('离舰成功','雷达发现敌机，进入作战空域','TAKEOFF COMPLETE');}}

function updateCamera(dt){const portrait=innerWidth<innerHeight;camera.fov=portrait?62:51;camera.updateProjectionMatrix();if(phase==='menu'){
    const drift=Math.sin(clockTime*.1)*2;cameraTarget.set(portrait?23:33,portrait?27:25,portrait?67:81);cameraTarget.x+=drift;camera.position.lerp(cameraTarget,Math.min(1,dt*2));lookTarget.set(portrait?-9:-23,portrait?14:13,portrait?8:-20);camera.lookAt(lookTarget);
  }else{const launch=phase==='launch'||phase==='paused'&&previousPhase==='launch';const back=portrait?38:34;cameraTarget.copy(jet.position).add(V(launch?3:0,launch?7:10,back));camera.position.lerp(cameraTarget,Math.min(1,dt*(launch?3.5:6)));if(shake>0&&phase!=='paused'){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;shake=Math.max(0,shake-dt*1.7);}lookTarget.copy(jet.position).add(V(move.x*7,5+move.y*5,-105));camera.lookAt(lookTarget);}
}
function updateMarkers(){const valid=boss&&boss.hp>0?[...enemies,boss]:enemies;for(const e of valid){const p=e.mesh.position.clone();if(e.isBoss)p.y=20;projected.copy(p).project(camera);if(projected.z<0||projected.z>1||Math.abs(projected.x)>1.1||Math.abs(projected.y)>1.1){markers.get(e)?.classList.add('hidden');continue;}let marker=markers.get(e);if(!marker){marker=document.createElement('div');marker.className='target-marker';marker.innerHTML='<span></span>';$('target-layer').appendChild(marker);markers.set(e,marker);}marker.classList.remove('hidden');marker.classList.toggle('locked',e===target);marker.style.left=`${(projected.x*.5+.5)*innerWidth}px`;marker.style.top=`${(-projected.y*.5+.5)*innerHeight}px`;marker.querySelector('span').textContent=`${e===target?'锁定 · ':''}${Math.round(jet.position.distanceTo(p))} m`;}
}
const radar=$('radar'),radarCtx=radar.getContext('2d');
function drawRadar(){const c=radarCtx,s=220,r=94,cx=110,cy=108;c.clearRect(0,0,s,s);c.fillStyle='rgba(6,24,32,.28)';c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.fill();c.strokeStyle='rgba(148,211,199,.25)';c.lineWidth=1;for(const radius of [r/3,r*2/3,r]){c.beginPath();c.arc(cx,cy,radius,0,Math.PI*2);c.stroke();}c.strokeStyle='rgba(148,211,199,.17)';c.beginPath();c.moveTo(cx-r,cy);c.lineTo(cx+r,cy);c.moveTo(cx,cy-r);c.lineTo(cx,cy+r);c.stroke();const angle=clockTime*1.5;const g=c.createConicGradient(angle,cx,cy);g.addColorStop(0,'rgba(112,232,190,.18)');g.addColorStop(.17,'rgba(112,232,190,0)');g.addColorStop(1,'rgba(112,232,190,0)');c.fillStyle=g;c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.fill();c.fillStyle='#a2fbe0';c.beginPath();c.moveTo(cx,cy-5);c.lineTo(cx+4,cy+5);c.lineTo(cx,cy+2);c.lineTo(cx-4,cy+5);c.closePath();c.fill();for(const e of boss&&boss.hp>0?[...enemies,boss]:enemies){const dx=(e.mesh.position.x-jet.position.x)*.18,dz=(e.mesh.position.z-jet.position.z)*.11;const len=Math.hypot(dx,dz),factor=Math.min(1,(r-8)/len);c.fillStyle=e===target?'#aaffda':'#efa881';c.beginPath();c.arc(cx+dx*factor,cy+dz*factor,e.isBoss?4:2.5,0,Math.PI*2);c.fill();}c.fillStyle='#90b9ba';c.font='11px sans-serif';c.textAlign='center';c.fillText('N',cx,9);}
function updateHUD(){ $('health-number').textContent=Math.round(hp);$('health-fill').style.width=`${hp}%`;$('health-fill').style.background=hp<30?'#ff9b7d':'#83f2df';$('kills').textContent=String(kills).padStart(2,'0');$('score').textContent=String(score).padStart(5,'0');$('missile-count').textContent=`${ammo} / 8`;$('flare-count').textContent=`${flares} / 3`;$('speed').textContent=String(Math.round(Math.abs(aircraftVelocity.z)*3.6)).padStart(3,'0');$('altitude').textContent=String(Math.round(jet.position.y)).padStart(3,'0');$('target-count').textContent=`${enemies.length+(boss&&boss.hp>0?1:0)} TGT`;$('missile').classList.toggle('cooling',missileCooldown>0);$('flare').classList.toggle('cooling',flareCooldown>0); }

function updateGame(dt){time+=dt;invincible=Math.max(0,invincible-dt);flareTime=Math.max(0,flareTime-dt);missileCooldown=Math.max(0,missileCooldown-dt);flareCooldown=Math.max(0,flareCooldown-dt);ammoTimer+=dt;flareTimer+=dt;if(ammoTimer>=8){ammoTimer=0;ammo=Math.min(8,ammo+1);}if(flareTimer>=28){flareTimer=0;flares=Math.min(3,flares+1);}updatePlayer(dt);
  if(time<100){const next=waveAt(time);if(next!==wave){wave=next;if(wave>1){banner(`第 ${wave} 波接敌`,wave===4?'敌方编队正在集中':'保持机动，逐个击破',`WAVE 0${wave}`);ammo=Math.min(8,ammo+2);}$('mission-detail').textContent=`拦截编队 · 波次 ${wave} / 4`;}spawnTimer-=dt;if(spawnTimer<=0){spawnTimer=Math.max(2.8,5-wave*.45);spawnEnemy();if(wave>=2)spawnEnemy(25);if(wave===4)spawnEnemy(-30);}}else if(!boss)spawnBoss();
  target=getTarget();gunTimer-=dt;if(gunTimer<=0){gunTimer=.16;shootGun();}if(keys.has('Space'))fireMissile();updateEnemies(dt);updateBullets(dt);updateMissiles(dt);
}

function resetJoystick(){joy.id=null;joy.x=joy.y=0;$('joy-stick').style.transform='translate(0,0)';}
function joystickMove(e){if(e.pointerId!==joy.id)return;const r=$('joystick').getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,max=r.width*.34,d=Math.hypot(x,y),scale=d>max?max/d:1;joy.x=x*scale/max;joy.y=y*scale/max;$('joy-stick').style.transform=`translate(${x*scale}px,${y*scale}px)`;}
$('joystick').addEventListener('pointerdown',e=>{if(phase!=='play'||joy.id!==null)return;e.preventDefault();joy.id=e.pointerId;$('joystick').setPointerCapture(e.pointerId);joystickMove(e);});$('joystick').addEventListener('pointermove',joystickMove);for(const name of ['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(name,e=>{if(e.pointerId===joy.id)resetJoystick();});
$('missile').addEventListener('pointerdown',e=>{e.preventDefault();fireMissile();});$('flare').addEventListener('pointerdown',e=>{e.preventDefault();releaseFlares();});$('missile').addEventListener('click',fireMissile);$('flare').addEventListener('click',releaseFlares);
$('launch').addEventListener('click',start);$('restart').addEventListener('click',start);$('restart-pause').addEventListener('click',start);$('return').addEventListener('click',menu);$('resume').addEventListener('click',resume);$('pause-button').addEventListener('click',pause);$('sound').addEventListener('click',toggleSound);document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();if(phase==='menu')return;pause();});
$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('game').requestFullscreen();}catch{showToast('此浏览器不支持全屏，可横屏游玩');}});
$('quality').addEventListener('click',()=>{quality=quality==='auto'?'high':quality==='high'?'low':'auto';$('quality-label').textContent={auto:'自动',high:'精细',low:'流畅'}[quality];const d=quality==='high'?Math.min(devicePixelRatio,2):quality==='low'?1:Math.min(devicePixelRatio,isTouch?1.3:1.7);renderer.setPixelRatio(d);renderer.shadowMap.enabled=quality!=='low';renderer.setSize(innerWidth,innerHeight);showToast({auto:'自动画质 · 平衡清晰度与性能',high:'精细画质 · 更清晰的海面与战机',low:'流畅画质 · 降低渲染负担'}[quality]);});
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','KeyF','KeyP','Escape','Enter'].includes(e.code))e.preventDefault();if(e.code==='Enter'&&['menu','victory','defeat'].includes(phase)){start();return;}if((e.code==='KeyP'||e.code==='Escape')&&!e.repeat){phase==='paused'?resume():pause();return;}if(e.code==='KeyF'&&!e.repeat)releaseFlares();keys.add(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();resetJoystick();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);particles.mesh.material.uniforms.pixelScale.value=innerHeight*.55;});
document.addEventListener('contextmenu',e=>e.preventDefault());

// The optional browser tool registry uses the exact same visible game actions.
const context=document.modelContext;
if(context?.registerTool){const controller=new AbortController();const register=(tool)=>{try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}};
  register({name:'read_flight_state',title:'读取飞行状态',description:'Read the current game phase, health, score, wave, weapons and mission time.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No arguments expected.');return {phase,health:hp,score,kills,wave,missiles:ammo,flares,seconds:Math.floor(time)};}});
  register({name:'start_flight',title:'开始出击',description:'Start or restart the J-35 carrier takeoff using the visible launch action.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No arguments expected.');if(!loaded||!['menu','victory','defeat'].includes(phase))throw new Error('Flight is not ready to start.');start();return {phase};}});
  window.addEventListener('pagehide',()=>controller.abort(),{once:true});
}

let last=performance.now(),frameCount=0,fpsClock=0,autoTuned=false;
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;const running=phase!=='paused';if(running){clockTime+=dt;if(phase==='launch')updateLaunch(dt);else if(phase==='play')updateGame(dt);particles.update(dt);toastTimer-=dt;if(toastTimer<=0)$('toast').classList.remove('visible');bannerTimer-=dt;if(bannerTimer<=0)$('wave-banner').classList.remove('visible');damageAlpha=Math.max(0,damageAlpha-dt*1.4);$('damage-flash').style.opacity=String(damageAlpha);}
  updateCamera(dt);world.update(clockTime,camera.position,jet.position);shadow.position.x=jet.position.x;shadow.position.z=jet.position.z;shadow.material.opacity=jet.position.y<20?.38:.16;shadow.scale.setScalar(1+jet.position.y*.012);shadow.visible=jet.visible;updateMarkers();uiTimer-=dt;if(uiTimer<=0){uiTimer=.12;updateHUD();drawRadar();}if(engineGain&&audio){const gain=soundEnabled&&['launch','play'].includes(phase)?.047:0;engineGain.gain.setTargetAtTime(gain,audio.currentTime,.12);engineOsc.frequency.setTargetAtTime(phase==='launch'?42+launchTime*7:80+move.y*6,audio.currentTime,.1);}renderer.render(scene,camera);
  if(!autoTuned&&quality==='auto'&&phase==='play'){frameCount++;fpsClock+=dt;if(fpsClock>4){if(frameCount/fpsClock<34){renderer.setPixelRatio(1);renderer.shadowMap.enabled=false;renderer.setSize(innerWidth,innerHeight);$('quality-label').textContent='流畅';}autoTuned=true;}}
}
reset();camera.position.set(30,26,85);world.ready.then(()=>{loaded=true;$('launch').disabled=false;$('launch-label').textContent='开始出击';});requestAnimationFrame(frame);
window.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();$('error-message').textContent='图形渲染已中断，请重新加载游戏，或切换流畅画质。';setUI('error-screen',true);});
